version: '3.8'

volumes:
  tg_bot_postgres_data: {}
  tg_bot_postgres_data_backups: {}
  static_data: {}

networks:
  tg_bot_network:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: tg_bot_django_image:latest
    container_name: tg_bot_django_container
    restart: unless-stopped
    command: /scripts/run
    volumes:
      - static_data:/app/vol
      - ./app/:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - tg_bot_network

  postgres:
    image: postgres:15.5-alpine3.18
    container_name: tg_bot_postgres_container
    restart: unless-stopped
    volumes:
      - tg_bot_postgres_data:/var/lib/postgresql/data:cached
      - tg_bot_postgres_data_backups:/backups:cached
    env_file:
      - ./.env
    networks:
      - tg_bot_network
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432

  redis:
    image: redis:alpine3.18
    container_name: tg_bot_redis_container
    restart: unless-stopped
    networks:
      - tg_bot_network
    expose:
      - "6379"
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    image: tg_bot_celery_worker_image:latest
    container_name: tg_bot_celery_worker_container
    restart: unless-stopped
    ports: []
    command: /scripts/start-celeryworker
    networks:
      - tg_bot_network
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  celery-beat:
    <<: *django
    image: tg_bot_celery_beat_image:latest
    container_name: tg_bot_celery_beat_container
    restart: unless-stopped
    ports: []
    command: /scripts/start-celerybeat
    networks:
      - tg_bot_network
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  flower:
    <<: *django
    image: tg_bot_celery_beat_image:latest
    container_name: tg_bot_celery_flower_container
    restart: unless-stopped
    command: /scripts/start-flower
    networks:
      - tg_bot_network
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    ports:
      - "5555:5555"