# Generated by Django 5.0 on 2023-12-18 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(max_length=40, unique=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('en', 'English')], default='en', max_length=3)),
                ('step', models.SmallIntegerField(choices=[(1, 'Listing language'), (2, 'Main menu')])),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
