# Generated by Django 5.0 on 2023-12-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegramuser_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='step',
            field=models.SmallIntegerField(choices=[(1, 'Listing language'), (2, 'Edit language'), (3, 'Main menu')], default=1),
        ),
    ]
